### ISSUE TITLE
Release New Version to Crates.io

### ISSUE THREAD

**Issue by zicklag** [datrs/bitfield-rle#31]
Since `failure` is no longer supported, I would like to be able to use this crate without it. I noticed that the version on `master` uses `anyhow` instead, but it's not published to crates.io.

Could we get an update?

**Comment by zicklag** [comment]
Hey there! Just a friendly double-check on this issue. We're using this crate transitively through [GGRS](https://github.com/gschup/ggrs) on our game [Jumpy](https://github.com/fishfolk/jumpy) as well as in our game framework [Bones](https://github.com/fishfolk/bones) and we've been getting reports in CI regarding security issues with Failure, so we'd really like to be able to switch from it if possible, without publishing a fork to crates.io.

**Comment by MaxCWhitehead** [comment]
It looks like the bump to 0.2.0. here on git was done after removing failure crate, but on [crates.io ](https://crates.io/crates/bitfield-rle/0.2.0/dependencies) the dep on failure is still reported for 0.2.0, any chance there was a mixup in version released on crates.io?

**Comment by ttiurani** [comment]
I removed this dependency from hypercore during the migration to v10, so this crate got left behind. I don't really know anything about this code but it did indeed seem like publishing had been done from the wrong branch.

I now bumped version to 0.2.1 and published that, it now seems to not have the failure crate anymore, can you check now @zicklag ?

**Comment by zicklag** [comment]
That looks like it worked! We'll test it out with our codebase soon, I think that will be good. Thanks!
